### ISSUE TITLE
Add shortcodes to link to issues and pull-requests

### ISSUE THREAD

**Issue by jongleur1983** [seinoxygen/wp-github#12]
It would be nice to be able to link to a particular issue.
When writing about e.g. an enhancement idea or a patch for a github-hosted project, it's good style to provide a link to the corresponding issue or pull request.

With wp-github, I would like to see a shortcode, that enhances this link by state, thus a link to an issue can be augmented by issue state (closed, open, has pull-request, merged, and so on).

**Comment by moabi** [comment]
You can try this feature in the last version : 
https://github.com/moabi/wp-github/archive/master.zip

[github-issue username="yahoo" repository="pure" number="14"]
will allow to get a single issue and retrieve state and number

the shortcode for issues will show state, request will be on all states now (open,closed)

**Comment by jongleur1983** [comment]
thanks. Trying it currently - any chance to get current versions up in the wordpress plugin repository?

**Comment by jongleur1983** [comment]
good to see the functionality at all, but I don't like how you implemented it.
The shortcode generates an unordered list with one single bullet point for the issue.
A list is a list as it should list elements, a single-element list should therefore IMHO be an exception if it occurs at all.

Adding several issue links following each other produces a sequence of unordered lists, each with a single item, which is even worse.
Any chance to convince you to change that behaviour to produce some kind of inline element for the issue?

Currently you generate html like this:
 ```html
<ul class="wp-github">
  <li>
    <span class="wp-github-state closed">closed</span>
    <span class="wp-github-nb">#14</span>
    <a title="Buttons on site in the Forms page have 'notice' class in them." 
       href="https://github.com/yahoo/pure/issues/14" 
       target="_blank"> Buttons on site in the Forms page have 'notice' class in them.</a>
  </li>
</ul>
```

I would propose to change that to something like
```html
<span class="wp-github-issue">
  <span class="wp-github-state closed">closed</span>
  <span class="wp-github-nb">#14</span>
  <a title="Buttons on site in the Forms page have 'notice' class in them." 
     href="https://github.com/yahoo/pure/issues/14" 
     target="_blank"> Buttons on site in the Forms page have 'notice' class in them.</a>
</span>
```
It would be possible then to wrap that in lists by using the list in wordpress itself (which supports visual preview in the editor) or to use it as an inline link in the text.

I would be happy to contribute to that - ideally if these extensions could be more easily available in wordpress by updating the "original" plugin with the current version in the plugin repository as well.

**Comment by moabi** [comment]
ok, it makes sens, for single items, I removed ul html element to replace it with a div
for the push to svn wp repo I know @seinoxygen is trying to get some time to work on it
