### ISSUE TITLE
Recieving Object instead of Array

### ISSUE THREAD

**Issue by alex-carlson** [seinoxygen/wp-github#14]
Sometimes I get a php error saying array_slice() failed because it got an object instead of an array.  Any idea why this might be?

Warning: array_slice() expects parameter 1 to be array, object given in *****/wp-content/plugins/wp-github-master/inc/shortcodes.php on line 96

**Comment by moabi** [comment]
what's the plugin version ? this should be fixed now

**Comment by alex-carlson** [comment]
Version 1.2.3.  It usually works, I thought it might have to do with my php version, but I'm on 5.5.29, which should be fine.  The issue is pretty infrequent as well.  I'm stumped.

**Comment by moabi** [comment]
Could you test the last version (on a test website if possible) 1.2.5 here : https://github.com/moabi/wp-github/archive/master.zip

**Comment by alex-carlson** [comment]
Looks to be working now!  Thanks @moabi !
