### ISSUE TITLE
Issues List error: 404

### ISSUE THREAD

**Issue by bretonics** [seinoxygen/wp-github#17]
There's an error on the "issues" request made through the API. The structure looks right according to the API, but I'm not sure why it's not working...did it change?

**Comment by moabi** [comment]
I'll take a look at your commit as soon as I get some more time to work on it, good point for the gravatar profile...

**Comment by bretonics** [comment]
Sounds great. Yes, I saw you fixed the gravatar profile in #16 commit `2188d1` but noticed the widget.

Out of curiosity, was the "issues" shortcode working for you (no one else seemed to mention it)? It didn't for me until I made those changes.

**Comment by moabi** [comment]
Let me know if the update works so I can close the issue and push to wp repository

**Comment by bretonics** [comment]
This is different than what I did in PR #20 but it seems to be working with your commits alone, and the **issues** issue #17 is fixed accordingly.
