### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by MannusEtten** [seinoxygen/wp-github#21]
hello, do i have to create a client id and secret for the plugin to let it work?

**Comment by moabi** [comment]
not at all

**Comment by MannusEtten** [comment]
I added this text to my page "[github-issue username="MannusEtten" repository="BikeTouringGIS"]" and activate the plugin. But the result is that the plugin tells me "no issues".

**Comment by moabi** [comment]
Use github-issues : 
[github-issues username="MannusEtten" repository="BikeTouringGIS"]

Single issue is fetch by ID like this : 
[github-issue username="seinoxygen" repository="wp-github" number="14"]
