### ISSUE TITLE
Commits from all repos shortcode not updating

### ISSUE THREAD

**Issue by bretonics** [seinoxygen/wp-github#22]
Shortcode `[github-commits username="bretonics" repository="" limit="10"]` listing commits from all repos does not update. It seems to be stuck at some point in time.

New commits are not shown, even when commits are appearing using other shortcodes such as "commits for a specific repo", and clearing cache does not seem to fix the problem.

**Comment by moabi** [comment]
the issue should be fixed
https://github.com/seinoxygen/wp-github/commit/80c439a60ab6b81520e74f60c5e7f0996357c41f

**Comment by bretonics** [comment]
WP plugin update?

**Comment by moabi** [comment]
hi, the plugin is "normally up to date" in the wp repo,..not used to work with svn, I saw the versions were mixed...don't hesitate for the advices !
