### ISSUE TITLE
Is it possible to display content from a private branch? 

### ISSUE THREAD

**Issue by Virtuworks** [seinoxygen/wp-github#23]
I would like to show content of commits but not code itself like a live changelog to a public site but hiding the actual code changes.

**Comment by moabi** [comment]
@Virtuworks it's already possible to grab content from a private repo.
But I don't get what you mean by "hiding the actual code changes"
Please refer to the github API

**Comment by Virtuworks** [comment]
Here is what I meant but I went into the plugin code and changed it to not add the URL Link Anchor around a line of code. Would be good if there was an option to enable/disable this. Here is where I am using this plugin. It would be great to be able to also show the Release Label attached to the commit (so users know which build a specific commit was in. Also if we can show the date of the commit. Would also be good if we could hide MERGE rows. 

https://mspcontrol.org/changelog/

Is there a way to show more than 25 records or this a GitHub Limit?

**Comment by moabi** [comment]
@Virtuworks 
Hiding the commit link is quite specific I guess
here is a list of what is available: 
https://developer.github.com/v3/repos/commits/
I could think about adding options to show/hide nodes

25 is not a limit, we could use last_sha to add more commits

**Comment by Virtuworks** [comment]
I am not a developer but if some of these options could make it into plugin I would be willing to fund the development of it. If you can contact me to omara@virtuworks.com if interested we could talk about compensation for it. I am in a big need of showing public people commits from a private branch and letting them look through them (maybe even supporting paging if possible).

**Comment by Virtuworks** [comment]
The real need here is to create something like a changelog based on commits from GitHub. I love to work agile but it's a lot of work to manage a changelog file when you have 10 developers contributing multiple changesets a day. I am looking for a way to share the commits which I will make my devs be more descriptive with and hopefully if the commit's label can be shown or link the release number it can act as a changelog for end users to understand what has gotten fixed version to version. My whole build process is automated with Team city so a chagelog is additional interaction that I would like to avoid.

**Comment by Virtuworks** [comment]
Just checking back to see if their is any interest here for us to help cover time to improve this plugin.

**Comment by moabi** [comment]
@Virtuworks 
will check if it's possible to update

**Comment by moabi** [comment]
@Virtuworks 
I added an xperimental custom endpoint function, please download latest version from github test it and give feedback to me.

`[github-commits username="yahoo" repository="pure" limit="30" xtended="commit->committer->email,url,commit->committer->name"]`

xtended attributes works as a endpoint listing.
it will add a span with a class, with the value.

you can retrieve all the possibilities here :
 https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository

**Comment by Virtuworks** [comment]
Thanks will try later tonight if possible

**Comment by Virtuworks** [comment]
I've downloaded and updated and it shows nothing just blank. 

https://mspcontrol.org/changelog/

**Comment by moabi** [comment]
@Virtuworks can you paste your shortcode

**Comment by Virtuworks** [comment]
[github-commits username="Virtuworks" repository="pure" limit="30" xtended="commit->committer->email,url,commit->committer->name"]

**Comment by moabi** [comment]
I guess you don't have a repository PURE
...

**Comment by Virtuworks** [comment]
Yup! =) Sorry about that! It seems to work great! Last thing that would be good is ability to hide MERGE PULL REQUESTS is that possible? 

https://mspcontrol.org/changelog/

See here I would like to be able to hide all the Merge Commits from the list.

**Comment by Virtuworks** [comment]
Also the limit of responses is still 30? Anyway to get paged list?

**Comment by Virtuworks** [comment]
Is it possible to show a label that is associated with the commit? We label the commits with Labels for their Build number. I don't see how to do this.

**Comment by moabi** [comment]
@Virtuworks download the last release, 
pay attention, the format has change to json like:
`[github-commits username="Virtuworks" repository="modsecurity-whitelist-apps" limit="30" xtended='{"Date de commit": "commit:committer:date","Email committer": "commit:committer:email","Url de commit": "url"}']`

**Comment by Virtuworks** [comment]
I've updated to latest version of plugin. Did you have a chance to review my other comments? You can see latest output at the same link above.

**Comment by moabi** [comment]
Please open a new issue for any new concern
