### ISSUE TITLE
Can there be a setting to omit Merge Changesets from commits?

### ISSUE THREAD

**Issue by Virtuworks** [seinoxygen/wp-github#24]
We would like to be able to filter out Merge Changesets.

**Comment by moabi** [comment]
a commit is a commit...github's API from what I know do not specify directly if it's part of a merge, filter it with some text filtering option...

**Comment by Virtuworks** [comment]
They all start with word merge

**Comment by moabi** [comment]
Out of the plugin scope, sorry
