### ISSUE TITLE
Ability to display more than 30 records 

### ISSUE THREAD

**Issue by Virtuworks** [seinoxygen/wp-github#25]
Would be great for this to provide a pagable interface instead of maxing at 30 records.

**Comment by moabi** [comment]
Get the latest version, it will retrieve the last 100 commits which is the github API limit, 
no pagination is yet implemented in this plugin
TODO:
- pagination
- since/until parameters

**Comment by ffoodd** [comment]
Hi there,

As far as I understand, this issue has been fixed but from what I see, it has not been published on the WordPress plugin repository latest release, has it? 

I'm experiencing this trouble when using the `[github-repos]` shortcode. Or might this issue only fixes commits listing?

Thanks for your work!
