### ISSUE TITLE
Improve documentation: dependencies.

### ISSUE THREAD

**Issue by rufein** [seinoxygen/wp-github#7]
To improve the documentantion, you could add a section of dependencies. In my case, when i've activated the plugin, it was giving exceptions because the function curl_init() wasn`t declared. I've realized that plugin was using php_curl library. A line like this should be appear in you documentation.

Dependencies: php_curl extension must be activated in your php.ini

**Comment by moabi** [comment]
This will be fixed in the next release, 
use wp http api instead of curl
@seinoxygen

**Comment by seinoxygen** [comment]
Noted. Will try to commit to wordpress svn today.
