### ISSUE TITLE
Shortcode errors

### ISSUE THREAD

**Issue by bretonics** [seinoxygen/wp-github#9]
Warning: array_merge(): Argument #2 is not an array in...line 95

Warning: usort() expects parameter 1 to be array, null given in...line 102

Warning: array_slice() expects parameter 1 to be array, null given in...line 600

Warning: Invalid argument supplied for foreach() in...line 602

This is for file `github.php`

**Comment by naulacambra** [comment]
Using which shortcodes?

**Comment by seinoxygen** [comment]
Please provide more info. How're you using them? Paste the code.

**Comment by bretonics** [comment]
This happens using shortcode: [github-commits username="bretonics" limit="25"]

I believe it also happened with the repos shortcode, but currently I'm not using it, so I can't attest to it at this moment.

**Comment by moabi** [comment]
if still needed I fixed this on my fork

**Comment by seinoxygen** [comment]
Fixed in merge.
